---
- name: Our first playbook (first play)
  hosts: localhost

  tasks:

    - name: Use Ansible to "openstack image list"
      os_image_info:
        cloud: alta3cloud
      register: result

    - name: Show images
      debug:
        msg: "{{ result.openstack_image[0].id }}"
#msg: "{{ result.openstack_image[0].name }}"

    - name: Use Ansible to "openstack flavor list"
      os_flavor_info:
        cloud: alta3cloud
      register: flav_result

    - name: Show flavors
      debug:
        msg: "{{ flav_result.openstack_flavors[0].id  }}"
#msg: "{{ result.openstack_flavors[0].name }}"  

    - name:  Launch a VM using the info we gathered
      os_server:
        cloud: alta3cloud
        state: present
        name: ansible_vm1
        image: "{{ result.openstack_image[0].id }}"
        flavor: "{{ flav_result.openstack_flavors[0].id }}"
